-- V2 extraction migration. V1 extraction rows may be reset during private-alpha rollout,
-- but tables remain separate so future schema versions do not require destructive rewrites.
CREATE TABLE IF NOT EXISTS extracted_claims (
  id UUID PRIMARY KEY,
  result_id UUID NOT NULL REFERENCES extraction_results(id) ON DELETE CASCADE,
  claim_type TEXT NOT NULL,
  evidence_origin TEXT NOT NULL,
  evidence_type TEXT NOT NULL,
  study_context TEXT NOT NULL,
  polarity TEXT NOT NULL,
  direction TEXT NOT NULL,
  cancer_type TEXT,
  biomarker_mention TEXT,
  biomarker_normalized_guess TEXT,
  drug_or_intervention_mention TEXT,
  drug_normalized_guess TEXT,
  variant_mention TEXT,
  pathway_mention TEXT,
  cell_line_mention TEXT,
  species_or_model_mention TEXT,
  outcome_mention TEXT,
  outcome_measure_mention TEXT,
  statistical_evidence_mention TEXT,
  sample_size_mention TEXT,
  pmid TEXT,
  pmcid TEXT,
  section_title TEXT,
  section_type TEXT,
  paragraph_index INTEGER,
  sentence_index INTEGER,
  char_start INTEGER,
  char_end INTEGER,
  exact_evidence_sentence TEXT NOT NULL,
  evidence_context TEXT,
  review_priority TEXT,
  confidence NUMERIC NOT NULL,
  source_citation TEXT NOT NULL,
  source_url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS extracted_claims_result_idx ON extracted_claims(result_id);
CREATE INDEX IF NOT EXISTS extracted_claims_origin_type_idx ON extracted_claims(evidence_origin, evidence_type);
